[package]
name    = "boxmeout-market"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
proptest = []
testutils = ["soroban-sdk/testutils", "boxmeout-shared/testutils"]

[dependencies]
soroban-sdk     = { version = "20.0.0", features = ["alloc"] }
boxmeout-shared = { path = "../shared" }

[dev-dependencies]
proptest = "1.6"
soroban-sdk = { version = "20.0.0", features = ["testutils"] }
