[package]
name    = "boxmeout-shared"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
proptest = []
testutils = ["soroban-sdk/testutils"]

[dependencies]
soroban-sdk = { version = "20.0.0", features = ["alloc"] }

[dev-dependencies]
proptest = "1.6"
soroban-sdk = { version = "20.0.0", features = ["testutils"] }
